#!/bin/bash
# setup.sh — Initialize a fresh agentic_writer installation
set -e

echo "Setting up Agentic Writer..."

# Create required directories
mkdir -p library external_library drafts
mkdir -p .claude/personas
mkdir -p .claude/skills/personal-voice

# Placeholder files for empty dirs (git won't track empty dirs)
touch library/.gitkeep
touch external_library/.gitkeep
touch drafts/.gitkeep

# Create empty index files
cat > LIBRARY_INDEX.md << 'EOF'
# Library Index

_Populated automatically by the Archivist agent when you run it on your /library._

## Articles

## Themes & Stances
EOF

cat > RESEARCH_INDEX.md << 'EOF'
# Research Index

_Populated automatically by the Researcher agent after each research task._

## Indexed Research Packs
EOF

cat > EXTERNAL_LIBRARY_INDEX.md << 'EOF'
# External Library Index

_Populated automatically by the Archivist (External Library Mode) when you add articles to /external_library._

## Indexed Articles
EOF

cat > TOPICS.md << 'EOF'
# Article Topics

## Backlog

## In Progress

## Published
EOF

# Create personal-voice skill stub
cat > .claude/skills/personal-voice/skill.md << 'EOF'
# Personal Voice Skill

_This file is generated by the Stylist agent. Add your writing samples to /library, then run the Stylist to calibrate your voice profile._

Run: "Run the Stylist to update my voice profile"
EOF

echo ""
echo "Setup complete."
echo ""
echo "Next steps:"
echo "  1. Add your writing samples to /library"
echo "  2. Run the Archivist:  \"Run the Archivist on the library\""
echo "  3. Run the Stylist:    \"Run the Stylist to calibrate my voice\""
echo "  4. Start writing:      \"Research [your topic]\""
